### ISSUE TITLE
Failed to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by laoshaw** [rurban/ctl#24]
builds OK but failed to install on ubuntu 20.04.

NOTE I ignored the first line "error" output below as the makefile has hard-coded g++ and ignores my `CXX?=g++-11` settings, which should not complain about c++20.

```
~/downloads/ctl-202102$ sudo make install
g++: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++2a’?
./update-index.pl
ronn --manual "CTL Manual 202102" --organization=rurban/ctl < docs/numeric.md > docs/man/numeric.h.3
ronn --manual "CTL Manual 202102" --organization=rurban/ctl < docs/index.md > docs/man/index.h.3
warn: unrecognized inline tag: ["img"]
warn: unrecognized inline tag: ["img"]
Traceback (most recent call last):
	29: from /usr/bin/ronn:184:in `<main>'
	28: from /usr/bin/ronn:184:in `each'
	27: from /usr/bin/ronn:199:in `block in <main>'
	26: from /usr/bin/ronn:199:in `each'
	25: from /usr/bin/ronn:220:in `block (2 levels) in <main>'
	24: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:240:in `convert'
	23: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:245:in `to_roff'
	22: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:245:in `new'
	21: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:18:in `initialize'
	20: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:91:in `block_filter'
	19: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block_filter'
	18: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
	17: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
	16: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
	15: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block in block_filter'
	14: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:139:in `block_filter'
	13: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:243:in `inline_filter'
	12: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
	11: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
	10: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
	 9: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:243:in `block in inline_filter'
	 8: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:255:in `inline_filter'
	 7: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:243:in `inline_filter'
	 6: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
	 5: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
	 4: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
	 3: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:243:in `block in inline_filter'
	 2: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:247:in `inline_filter'
	 1: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:354:in `write'
/usr/lib/ruby/vendor_ruby/ronn/roff.rb:354:in `gsub': incompatible encoding regexp match (Windows-31J regexp with UTF-8 string) (Encoding::CompatibilityError)
make: *** [GNUmakefile:246: docs/man/index.h.3] Error 1
```

**Comment by rurban** [comment]
Seems to be caused by an too old or too new ronn version.

**Comment by rurban** [comment]
The reported failure is a ronn/ruby encoding bug that aborted `make install` before any header was copied, because `install` hard-depended on man page generation. Man generation is now best-effort (ronn failures no longer abort the build) and `install` unconditionally installs headers and docs. Verified with a stub ronn that always fails: all 25 headers and 28 doc files still install. Closing.
